# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: Czech Technical University in Prague

# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: CI ROS 1

# This determines when this workflow is run
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch: {}

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: noetic, ROS_REPO: testing, DOCKER_IMAGE: "ros:noetic-perception-focal"}
          - ROS_DISTRO: melodic
            ROS_REPO: testing
            DOCKER_IMAGE: "ros:melodic-perception-bionic"
            UPSTREAM_WORKSPACE: .github/ci.ros1-melodic.rosinstall
            AFTER_SETUP_UPSTREAM_WORKSPACE: 'cd $BASEDIR/target_ws/src/ros-utils; for d in *; do if [[ "$d" != "cras_cpp_common" ]]; then rm -rf "$d"; fi; done; cd $BASEDIR/target_ws/src/compass; for d in *; do if [[ "$d" != "compass_msgs" ]]; then rm -rf "$d"; fi; done; echo "yaml https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml" > /etc/ros/rosdep/sources.list.d/21-master.list && rosdep update --include-eol-distros --rosdistro melodic'
        os: ["ubuntu-24.04", "ubuntu-24.04-arm"]
    name: "${{ matrix.env.ROS_DISTRO }}-${{ matrix.os }}"
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache # Directory for ccache (and how we enable ccache in industrial_ci)
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      # This step will fetch/store the directory used by ccache before/after the ci run
      - name: Cache ccache
        uses: rhaschke/cache@main
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.os }}-${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.ROS_REPO }}-${{ github.sha }}-${{ github.run_id }}
          restore-keys: |
            ccache-${{ matrix.os }}-${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.ROS_REPO }}-${{ github.sha }}
            ccache-${{ matrix.os }}-${{ matrix.env.ROS_DISTRO }}
        env:
          GHA_CACHE_SAVE: always
      # Run industrial_ci
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}